name: pet_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter     

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  google_fonts: ^3.0.1
  badges: ^2.0.3
  flutter_svg: ^1.1.6
  glassmorphism_ui: ^0.3.0
  i18n_extension: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/